
apiVersion: v1
kind: Pod
metadata: 
  name: testing
  namespace: tarzan
  labels:
    name: testing
spec:
  containers:
  - name: container-testing
    image: bitbull/webserver
    ports: 
    - containerPort: 80